. /etc/ksh.kshrc

export LANG=en_US.UTF-8
#export http_proxy=http://192.168.1.1:8118
#export https_proxy=http://192.168.1.1:8118

alias ls='ls -F'
alias ll='ls -lAF'
alias gits='git status'
alias urxvt='urxvt -bg black -fg white +sb -font 9x15'
